image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-ibank.jar    &

build_script:
  - java -jar app-ibank.jar -P:profile=test
  - chmod +x gradlew  
  - ./gradlew test -Dselenide.headless=true --info
